osx_image: xcode8.3
xcode_workspace: Reflex.xcworkspace
matrix:
  include:

    - xcode_scheme: Reflex macOS
      language: swift
      env:
        - XCODE_SDK=macosx10.12
        - XCODE_ACTION="test"
        - XCODE_DESTINATION="arch=x86_64"

    - xcode_scheme: Reflex iOS
      language: swift
      env:
        - XCODE_SDK=iphonesimulator10.3
        - XCODE_ACTION="test"
        - XCODE_DESTINATION="platform=iOS Simulator,OS=10.3,name=iPhone 6"

    - xcode_scheme: Reflex tvOS
      language: swift
      env:
        - XCODE_SDK=appletvsimulator10.2
        - XCODE_ACTION="test"
        - XCODE_DESTINATION="platform=tvOS Simulator,OS=10.2,name=Apple TV 1080p"

    - xcode_scheme: Reflex watchOS
      language: swift
      env:
        - XCODE_SDK=watchsimulator3.2
        - XCODE_ACTION="build" 
        - XCODE_DESTINATION="platform=watchOS Simulator,name=Apple Watch - 38mm"
after_success:
    - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725